[metadata]
name = sortnstore
version = 1.0.0

[options]
packages = find:
package_dir =
    = src
python_requires = >=3.8
zip_safe = False

[options.packages.find]
where = src

[flake8]
max-line-length = 120
exclude = .git, __pycache__, docs, .venv
ignore = E203, W503

[mypy]
python_version = 3.8
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = False
